<?php

namespace IslamBundle\Repository;

/**
 * ActiviteitenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteitenRepository extends \Doctrine\ORM\EntityRepository
{
}
